### PR TITLE
Use JDK 8 from debian package

### PR DESCRIPTION
**Pull request by johanandren**
Avoiding the annoying jabba outages

### CODE REVIEW

**Review by raboof — APPROVED** [review]
fine by me (though did we see them a lot since #131 ?)

**Comment by raboof** [comment]
I guess this means we now also release with jdk11 rather than jdk8?

**Comment by johanandren** [comment]
Ah, it should perhaps be jdk8 rather, good catch

**Comment by johanandren** [comment]
I don't think there is a huge benefit to testing with jdk11, we can just do all with jdk8

**Pull request merged**
